name: CI/CD

# Controls when the action will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # A job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup Node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

  # A job called "deploy"
  deploy:
    # "deploy" needs "build" to be successful
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy to GitHub Pages
        run: |
          git config user.email "jojo@theruntime.org"
          git config user.name "jojotrujillo"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          npm run deploy
